### ISSUE TITLE
glm compatibility for latest openFrameworks

### ISSUE THREAD

**Issue by interior-night** [nama-gatsuo/ofxDeferredShading#1]
Hi. Would it be possible to update the code to make it work with openFramework's [new glm syntax](http://openframeworks.cc/learning/02_graphics/how_to_use_glm/)?
I've tried but haven't quite succeeded.

`ofMatrix4x4` becomes `glm::mat4`
`ofVec3f` becomes `glm::vec3`
etc.

Some of the changes are less straightforward.

For example a line like:
`ofMatrix4x4 normalMatrix = ofMatrix4x4::getTransposedOf(cam.getModelViewMatrix().getInverse());`
I think becomes:
`glm::mat4 normalMatrix = glm::transpose(glm::inverse(cam.getModelViewMatrix()));`

This might also help: [hamoid fork of ofDeferredRendering](https://github.com/hamoid/of-DeferredRendering/commit/16ea4b29aeb9c126f38e34b0f553e5ab07c7bb8a)

Cheers!

**Comment by nama-gatsuo** [comment]
Ah, thank you for a nice mention. I will try to rewrite.
It may take some time so please wait in relax...

**Comment by phaseIV** [comment]
`        ofMatrix4x4 normalMatrix = ofMatrix4x4::getTransposedOf(ofMatrix4x4::getInverseOf(cam.getModelViewMatrix()));
`
FYI

**Comment by phaseIV** [comment]
Not sure about the glm stuff, but this seems to work;
`        ofMatrix4x4 normalMatrix = ofMatrix4x4::getTransposedOf(ofMatrix4x4::getInverseOf(cam.getModelViewMatrix()));
`
