### ISSUE TITLE
How to build the project?

### ISSUE THREAD

**Issue by trsh** [nama-gatsuo/ofxDeferredShading#6]
or example?

**Comment by nama-gatsuo** [comment]
It's just an [openFrameworks](https://openframeworks.cc/) (let me call as 'oF') addon. Users are supposed to have oF downloaded and to know how to build the project in ofxAddon's manner.

Let me give some references:
* [how to create oF project with ProjectGenerator](https://openframeworks.cc/learning/01_basics/create_a_new_project/)
* [how to add ofxAddon to your project](https://openframeworks.cc/learning/01_basics/how_to_add_addon_to_project/) 

The example of this addon is located in `/example` so you can build it in the same way.
