### ISSUE TITLE
Not working with GL 4,1

### ISSUE THREAD

**Issue by alptugan** [nama-gatsuo/ofxDeferredShading#7]
Thanks for the addon. I tried to run example with 4,1. Because, my GPU doesn't support 4,5. But, no success. Running on MAC OS X (High Sierra), btw. 
![Screen Shot 2020-04-02 at 17 53 15](https://user-images.githubusercontent.com/315287/78263697-f9d79780-750a-11ea-85be-3ffc2d46e970.png)

**Comment by nama-gatsuo** [comment]
Hi,

Thank you for letting me know.

The function `ofTexture::bindAsImage()` which is internally calling [`glBindImageTexture`](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBindImageTexture.xhtml) supports only OpenGL 4.2 and later that I didn't know about.

Currently this addon doesn't offer lower compatibility but little comment out should help to work.
Try comment outing or add compiler condition [line 192 to 211 in `src/pass/DofPass`](https://github.com/nama-gatsuo/ofxDeferredShading/blob/bfbe341472d2597b15ac0fff1c0d6a03b4d828f0/src/pass/DofPass.cpp#L192)

```C++
void DofPass::calcBokeh(const ofTexture& read) {
#if !defined(TARGET_OPENGLES) && defined(glBindImageTexture)
	// Bind textures to store
	bokehColorTex.bindAsImage(0, GL_WRITE_ONLY);
	bokehPosDepthCocTex.bindAsImage(1, GL_WRITE_ONLY);
	atomicBuffer.bind();

	detectBokehShader.begin();
	detectBokehShader.setUniformTexture("tex", read, 0);
	detectBokehShader.setUniformTexture("depthTex", depth.getTexture(), 1);

	detectBokehShader.setUniform1f("cocThres", bokehCocThres.get());
	detectBokehShader.setUniform1f("lumThres", bokehLumThres.get());
	detectBokehShader.setUniform1f("farEndCoc", endPointsCoC->y);
	detectBokehShader.setUniform1f("foculRangeEnd", foculRange->y);
	detectBokehShader.dispatchCompute(read.getWidth(), read.getHeight(), 1);
	detectBokehShader.end();

	bokehColorTex.unbind();
	bokehPosDepthCocTex.unbind();
	atomicBuffer.unbind();
#endif
}

``` 

This change will avoid bokeh rendering in DofPass but almost all features will work anyway.

**Comment by alptugan** [comment]
Hi,
Actually, I'd tried your suggestions. But, I didn't go further. Thanks! Now, it's compiling with 4.1 with the following codes in src/pass/DofPass;
```
void DofPass::calcBokeh(const ofTexture& read) {
	// Bind textures to store
	/*bokehColorTex.bindAsImage(0, GL_WRITE_ONLY);
	bokehPosDepthCocTex.bindAsImage(1, GL_WRITE_ONLY);
	atomicBuffer.bind();

	detectBokehShader.begin();
	detectBokehShader.setUniformTexture("tex", read, 0);
	detectBokehShader.setUniformTexture("depthTex", depth.getTexture(), 1);

	detectBokehShader.setUniform1f("cocThres", bokehCocThres.get());
	detectBokehShader.setUniform1f("lumThres", bokehLumThres.get());
	detectBokehShader.setUniform1f("farEndCoc", endPointsCoC->y);
	detectBokehShader.setUniform1f("foculRangeEnd", foculRange->y);
	detectBokehShader.dispatchCompute(read.getWidth(), read.getHeight(), 1);
	detectBokehShader.end();

	bokehColorTex.unbind();
	bokehPosDepthCocTex.unbind();
	atomicBuffer.unbind();*/
}

void DofPass::renderBokeh() {

	bokehRenderShader.begin();
	bokehRenderShader.setUniformTexture("bokehColor", bokehColorTex, 1);
	bokehRenderShader.setUniformTexture("bokehPosDepthCoc", bokehPosDepthCocTex, 2);
	bokehRenderShader.setUniformTexture("bokehTex", bokehShapeTex.getTexture(), 3);
	bokehRenderShader.setUniform1f("maxBokehRadius", maxBokehRadius);
	bokehRenderShader.setUniform1f("bokehDepthCutoff", bokehDepthCutoff);
	//atomicBuffer.drawIndirect(vbo.getVbo(), GL_TRIANGLE_STRIP);
	bokehRenderShader.end();

}
```

**Comment by yatara-visuals** [comment]
Hi all ! 
Thanks a lot for this addon. However, my computer also doesn't support GL versions further than 4.1. I tried to comment out the lines as @alptugan suggests, it compiles, but I get a white screen ( and some previews on the lower part of the screen). 

Any suggestions on how to make it work ?

<img width="1272" alt="Capture d’écran 2020-04-11 à 12 33 55" src="https://user-images.githubusercontent.com/62895492/79041572-279a9b80-7bf1-11ea-9919-cf696caf5aa0.png">

**Comment by yatara-visuals** [comment]
Also I get the following error log :

**[ error ] ofShader: setupShaderFromSource(): GL_FRAGMENT_SHADER shader failed to compile
[ error ] ofShader: GL_FRAGMENT_SHADER shader reports:
ERROR: 0:1: '' :  version '430' is not supported
ERROR: 0:1: '' : syntax error: #version
ERROR: 0:2: '' :  #version required and missing.
ERROR: 0:3: '0' : syntax error: integers in layouts require GLSL 140 or later

[ error ] ofShader: GL_FRAGMENT_SHADER, offending line 1 :
	    1	#version 430 core
	    2	
	    3	layout (binding = 0) uniform sampler2DRect tex;

[ error ] ofShader: checkProgramLinkStatus(): program failed to link
[ error ] ofShader: ofShader: program reports:
ERROR: One or more attached shaders not successfully compiled

[ error ] ofShader: setupShaderFromSource(): failed creating GL_COMPUTE_SHADER shader
[ error ] ofShader: setupShaderFromSource(): failed creating GL_COMPUTE_SHADER shader**

**Comment by alptugan** [comment]
What's the major/minor version in your main.cpp in your project? It should be 4,1

**Comment by yatara-visuals** [comment]
Yeah it is 4,1

**Comment by alptugan** [comment]
@yatara-visuals  I also got shader issues, btw. But, the result is good enough for me. I suggest you try to find problematic shader methods in the code. Just comment all the shader based methods in your ofApp.cpp. Then, comment out these lines one-by-one in order to identify problematic methods. May be your GPU doesn't support some other methods. You can check your graphics card capabilities via [opengGL View App](http://www.realtech-vr.com/home/glview)
